import type { BespokeReportDef } from "@/types/admin-bespoke-report";

/**
 * Registry of the ~29 `ReportsController` endpoints that call
 * `makePaginatedResponse()` (standard envelope, generic dynamic-column
 * table works for all of them). The other ~7 endpoints (audit mutation,
 * 3 key/value-list dashboards, sorting-report create/view/delete) are wired
 * individually in `app/admin/(portal)/reports/page.tsx` — see the
 * `BespokeReportsTab` component there for how they attach to this registry
 * (e.g. the "audit" mutation widget renders above the `audit-list` report,
 * the sorting-report CRUD trio renders around the `sorting-reports-list`
 * report).
 *
 * `pathParams` (if present) lists filter keys, in order, that get appended
 * as URL path segments (e.g. `client-count/list/{yearmonth}`) rather than
 * sent as query params — matches the few endpoints with a route like
 * `.../list/{param}` or `.../view/{a}/{b}`.
 */
export const BESPOKE_REPORTS: BespokeReportDef[] = [
  {
    id: "audit-list",
    group: "Administrative",
    title: "Audit report",
    description: "Orders cleared from manifesto but not yet audited at HO.",
    permissions: ["view-audit-report"],
    path: "audit/list",
    filters: [
      { key: "branch_id", label: "Branch", type: "branch" },
      { key: "requestedDate", label: "Date range", type: "daterange" },
      { key: "order_no", label: "Order no.", type: "text" },
      { key: "waybill_id", label: "Waybill", type: "text" },
      { key: "customer_name", label: "Customer name", type: "text" },
      { key: "address", label: "Address", type: "text" },
      { key: "branch_name", label: "Branch name", type: "text" },
    ],
  },
  {
    id: "client-count-dashboard",
    group: "Administrative",
    title: "Client count (yearly / monthly / weekly)",
    description: "Fixed 3-row summary of new client registrations.",
    permissions: ["view-client-count-report"],
    path: "client-count/dashboard",
    filters: [],
  },
  {
    id: "client-count",
    group: "Administrative",
    title: "Client count by month",
    description: "Monthly new-client registration counts.",
    permissions: ["view-client-count-report"],
    path: "client-count",
    filters: [{ key: "month_name", label: "Month name", type: "month-name" }],
  },
  {
    id: "client-count-list",
    group: "Administrative",
    title: "Client count — month detail",
    description: "Clients registered in a specific year-month (drill-down from the monthly report).",
    permissions: ["view-client-count-report"],
    path: "client-count/list",
    pathParams: ["yearmonth"],
    filters: [
      { key: "yearmonth", label: "Year-Month (e.g. 2026-August)", type: "text", required: true },
      {
        key: "client_status",
        label: "Client status",
        type: "select",
        options: [
          { value: "new", label: "New" },
          { value: "active", label: "Active" },
          { value: "deactivated", label: "Deactivated" },
        ],
      },
      { key: "customer_name", label: "Business name", type: "text" },
      { key: "address", label: "Address", type: "text" },
      { key: "pick_address", label: "Pickup address", type: "text" },
      { key: "email", label: "Email", type: "text" },
    ],
  },
  {
    id: "sales-quantity",
    group: "Administrative",
    title: "Sales quantity by branch",
    description: "Order count and COD totals per branch.",
    permissions: ["view-sales-quantity-report"],
    path: "sales-quantity",
    filters: [
      { key: "client_id", label: "Client", type: "client" },
      { key: "branch_name", label: "Branch name", type: "text" },
    ],
  },
  {
    id: "sales-report",
    group: "Administrative",
    title: "Sales report (monthly)",
    description: "Monthly delivery-charge and commission totals across all invoices.",
    permissions: ["view-sales-report"],
    path: "sales-report",
    filters: [
      { key: "requestedDate", label: "Date range", type: "daterange" },
      { key: "month_name", label: "Month name", type: "month-name" },
    ],
  },
  {
    id: "sales-report-view",
    group: "Administrative",
    title: "Sales report — month detail",
    description: "Order-level detail for a specific invoice month (drill-down from the sales report).",
    permissions: ["view-sales-report"],
    path: "sales-report/view",
    pathParams: ["year", "month"],
    filters: [
      { key: "year", label: "Year (e.g. 2026)", type: "text", required: true },
      { key: "month", label: "Month (e.g. 08 or August)", type: "text", required: true },
      { key: "waybill_id", label: "Waybill", type: "text" },
      { key: "invoice_no", label: "Invoice no.", type: "text" },
    ],
  },
  {
    id: "client-deactivation-details",
    group: "Administrative",
    title: "Client deactivation forecast",
    description: "Active clients projected to deactivate based on last-order date.",
    permissions: ["view-client-deactivation-report"],
    path: "client-deactivation-details",
    filters: [
      { key: "client_id", label: "Client", type: "client" },
      { key: "requestedDate", label: "Date range", type: "daterange" },
      { key: "client_number", label: "Client no.", type: "text" },
      { key: "client_name", label: "Client name", type: "text" },
      { key: "address", label: "Address", type: "text" },
      { key: "email", label: "Email", type: "text" },
    ],
  },
  {
    id: "inactive-client-count",
    group: "Administrative",
    title: "Inactive client count (by period)",
    description: "Fixed 5-bucket summary of clients bucketed by months since last order.",
    permissions: ["view-inactive-client-count-report"],
    path: "inactive-client-count",
    filters: [],
  },
  {
    id: "inactive-client-count-list",
    group: "Administrative",
    title: "Inactive clients — bucket detail",
    description: "Clients within a specific inactivity bucket (drill-down from the count summary).",
    permissions: ["view-inactive-client-count-report"],
    path: "inactive-client-count/list",
    pathParams: ["count"],
    filters: [
      {
        key: "count",
        label: "Bucket",
        type: "select",
        required: true,
        options: [
          { value: "count1", label: "1–3 months" },
          { value: "count2", label: "3–6 months" },
          { value: "count3", label: "6–9 months" },
          { value: "count4", label: "9–12 months" },
          { value: "count5", label: "Over 1 year" },
        ],
      },
      { key: "client_id", label: "Client", type: "client" },
      { key: "client_name", label: "Client name", type: "text" },
      { key: "pick_address", label: "Pickup address", type: "text" },
      { key: "email", label: "Email", type: "text" },
    ],
  },
  {
    id: "branch-progress-report",
    group: "Administrative",
    title: "Branch progress",
    description: "Pending / delivered / failed / returned counts per branch (yesterday snapshot).",
    permissions: ["view-branch-progress-report"],
    path: "branch-progress-report",
    filters: [
      { key: "branch_id", label: "Branch", type: "branch" },
      { key: "branch_name", label: "Branch name", type: "text" },
    ],
  },
  {
    id: "branch-manifest-summary-report",
    group: "Administrative",
    title: "Branch manifest summary (last 30 days)",
    description: "Per-branch order totals over the last 30 days.",
    permissions: ["view-branch-progress-report"],
    path: "branch-manifest-summary-report",
    filters: [{ key: "branch_name", label: "Branch name", type: "text" }],
  },
  {
    id: "client-status-report",
    group: "Status Detail",
    title: "Client status breakdown",
    description: "Order counts per status for a specific client (wide pivot table).",
    permissions: ["view-client-status-report"],
    path: "client-status-report",
    filters: [
      { key: "client_id", label: "Client", type: "client", required: true },
      { key: "client_name", label: "Client name", type: "text" },
    ],
  },
  {
    id: "branch-status-report",
    group: "Status Detail",
    title: "Branch status counts",
    description: "Live order count per status for a branch.",
    permissions: ["view-branch-status-report"],
    path: "branch-status-report",
    filters: [{ key: "branch_id", label: "Branch", type: "branch", required: true }],
  },
  {
    id: "branch-status-view",
    group: "Status Detail",
    title: "Branch status — order detail",
    description: "Order-level drill-down for one branch + status.",
    permissions: ["view-branch-status-report"],
    path: "branch-status/view",
    filters: [
      { key: "branch_id", label: "Branch", type: "branch", required: true },
      { key: "status", label: "Status", type: "primary-status", required: true },
      { key: "dateRange", label: "Date range", type: "daterange" },
      { key: "waybill_id", label: "Waybill", type: "text" },
      { key: "customer_name", label: "Customer name", type: "text" },
      { key: "client_name", label: "Client name", type: "text" },
      { key: "address", label: "Address", type: "text" },
      { key: "branch_name", label: "Branch name", type: "text" },
    ],
  },
  {
    id: "client-order-clearance",
    group: "Clearing & Pending",
    title: "Client order clearance",
    description: "Per-client cleared vs. not-cleared order counts.",
    permissions: ["view-client-clearance-report"],
    path: "client-order-clearance",
    filters: [{ key: "client_id", label: "Client", type: "client" }],
  },
  {
    id: "branch-order-clearance",
    group: "Clearing & Pending",
    title: "Branch order clearance",
    description: "Per-branch cleared vs. not-cleared order counts.",
    permissions: ["view-branch-clearance-report"],
    path: "branch-order-clearance",
    filters: [{ key: "branch_id", label: "Branch", type: "branch" }],
  },
  {
    id: "pending-order-days",
    group: "Clearing & Pending",
    title: "Pending orders by days-in-status",
    description: "Currently pending orders bucketed by days since their status last changed.",
    permissions: ["view-pending-order-report"],
    path: "pending-order-days",
    filters: [],
  },
  {
    id: "branch-user-clearance",
    group: "Clearing & Pending",
    title: "Branch-manager clearance",
    description: "Status-count breakdown for branches assigned to a branch manager.",
    permissions: ["view-user-clearance-report"],
    path: "branch-user-clearance",
    filters: [{ key: "branch_manger_id", label: "Branch manager", type: "staff" }],
  },
  {
    id: "branch-user-clearance-view",
    group: "Clearing & Pending",
    title: "Branch-manager clearance — order detail",
    description: "Order-level drill-down for a branch manager + status.",
    permissions: ["view-user-clearance-report"],
    path: "branch-user-clearance/view",
    filters: [
      { key: "staff_id", label: "Staff", type: "staff", required: true },
      { key: "status", label: "Status", type: "primary-status" },
    ],
  },
  {
    id: "client-order-pending",
    group: "Status Count",
    title: "Client pending calendar",
    description: "Per-client, per-day order counts for a status, across a date range.",
    permissions: ["view-client-pending-report"],
    path: "client-order-pending",
    filters: [
      { key: "dateRange", label: "Date range", type: "daterange", required: true },
      { key: "status", label: "Status", type: "primary-status", required: true },
    ],
  },
  {
    id: "branch-order-pending",
    group: "Status Count",
    title: "Branch pending calendar",
    description: "Per-branch, per-day order counts for a status, across a date range.",
    permissions: ["view-branch-pending-report"],
    path: "branch-order-pending",
    filters: [
      { key: "dateRange", label: "Date range", type: "daterange", required: true },
      { key: "status", label: "Status", type: "primary-status", required: true },
    ],
  },
  {
    id: "rider-order-pending",
    group: "Status Count",
    title: "Rider pending calendar",
    description: "Per-rider, per-day order counts for a status, across a date range.",
    permissions: ["view-rider-report"],
    path: "rider-order-pending",
    filters: [
      { key: "dateRange", label: "Date range", type: "daterange", required: true },
      { key: "status", label: "Status", type: "primary-status", required: true },
    ],
  },
  {
    id: "branch-income-report",
    group: "Finance",
    title: "Branch income",
    description: "Per-branch deposit / commission / expense summary.",
    permissions: ["view-branch-income-report"],
    path: "branch-income-report",
    filters: [
      { key: "dateRange", label: "Date range", type: "daterange" },
      { key: "branch_id", label: "Branch", type: "branch" },
    ],
  },
  {
    id: "return-report",
    group: "Finance",
    title: "Return report",
    description: "Delivered / returned totals per invoice for a configured set of clients.",
    permissions: ["view-return-report"],
    path: "return-report",
    filters: [{ key: "dateRange", label: "Date range", type: "daterange" }],
  },
  {
    id: "pending-invoice",
    group: "Finance",
    title: "Pending invoice (per client)",
    description: "Un-invoiced payable breakdown per client.",
    permissions: ["view-finance-invoice-pending-report"],
    path: "pending-invoice",
    filters: [{ key: "client_name", label: "Client name", type: "text" }],
  },
  {
    id: "processing-order-collecting-report",
    group: "Sorting",
    title: "Processing / collecting reconciliation",
    description: "Per-branch scan-reconciliation counts for one client's orders.",
    permissions: ["processing-order-collecting"],
    path: "processing-order-collecting-report",
    filters: [
      { key: "dateRange", label: "Date range", type: "daterange", required: true },
      { key: "client_id", label: "Client", type: "client", required: true },
    ],
  },
  {
    id: "today-clear-orders",
    group: "Sorting",
    title: "Today's clear orders",
    description: "Waybills processed today at a sorting layer or branch.",
    permissions: ["view-sort-processing-orders-today-report"],
    path: "today-clear-orders",
    filters: [
      { key: "sorting_layer_id", label: "Sorting layer", type: "sorting-layer" },
      { key: "branch_id", label: "Branch (used only if no layer selected)", type: "branch" },
    ],
  },
  {
    id: "all-clear-orders-history",
    group: "Sorting",
    title: "Clear orders history",
    description: "Waybills processed at a branch on a specific date.",
    permissions: ["view-sort-processing-orders-report"],
    path: "all-clear-orders-history",
    filters: [
      { key: "branch_id", label: "Branch", type: "branch", required: true },
      { key: "single_date", label: "Date", type: "date", required: true },
    ],
  },
  {
    id: "sorting-reports-list",
    group: "Sorting",
    title: "Saved sorting reports",
    description: "Named branch-group definitions used for processing-efficiency comparisons.",
    permissions: ["sorting-process-efficiency"],
    path: "sorting-reports/list",
    filters: [],
  },
];

export function findBespokeReport(id: string): BespokeReportDef | undefined {
  return BESPOKE_REPORTS.find((r) => r.id === id);
}
