"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, RefreshCw, Copy, Eye, EyeOff } from "lucide-react";
import {
  useClientApiInfo,
  useGenerateClientApiToken,
  useToggleClientWebhook,
} from "@/lib/hooks/use-admin-clients";
import { getErrorMessage } from "@/lib/api/client";
import { formatDate } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export function ClientApiTab({ clientId }: { clientId: number }) {
  const { data, isLoading, isError } = useClientApiInfo(clientId);
  const generateMutation = useGenerateClientApiToken(clientId);
  const webhookMutation = useToggleClientWebhook(clientId);
  const [reveal, setReveal] = useState(false);

  if (isLoading) return <Skeleton className="h-48 w-full" />;
  if (isError)
    return (
      <p className="py-6 text-sm text-muted-foreground">
        Couldn&apos;t load API details for this client.
      </p>
    );
  if (!data) return null;

  const token = data.api_token ?? "";
  const masked = token ? `${token.slice(0, 6)}${"•".repeat(Math.max(token.length - 6, 4))}` : "—";

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-base">API token</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-center gap-2">
            <code className="rounded-md bg-muted px-3 py-1.5 text-sm">
              {token ? (reveal ? token : masked) : "No token generated yet"}
            </code>
            {token && (
              <>
                <Button
                  size="icon-sm"
                  variant="ghost"
                  onClick={() => setReveal((r) => !r)}
                  title={reveal ? "Hide" : "Reveal"}
                >
                  {reveal ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
                </Button>
                <Button
                  size="icon-sm"
                  variant="ghost"
                  onClick={() => {
                    navigator.clipboard?.writeText(token);
                    toast.success("Token copied");
                  }}
                  title="Copy"
                >
                  <Copy className="size-4" />
                </Button>
              </>
            )}
          </div>
          <dl className="grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
            <div>
              <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Generated by
              </dt>
              <dd className="mt-0.5">{data.token_generated_by ?? "—"}</dd>
            </div>
            <div>
              <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Generated at
              </dt>
              <dd className="mt-0.5">{formatDate(data.token_generated_at)}</dd>
            </div>
          </dl>
          <Button
            variant="outline"
            disabled={generateMutation.isPending}
            onClick={() => {
              if (
                token &&
                !window.confirm(
                  "Generating a new token will invalidate the existing one. Continue?"
                )
              )
                return;
              generateMutation.mutate(undefined, {
                onSuccess: () => toast.success("New API token generated"),
                onError: (error) =>
                  toast.error(getErrorMessage(error, "Could not generate token")),
              });
            }}
          >
            {generateMutation.isPending ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <RefreshCw className="size-4" />
            )}
            Generate new token
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Webhook</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center justify-between gap-4">
          <p className="text-sm text-muted-foreground">
            {data.is_webhook_active
              ? "Webhook notifications are currently enabled for this client."
              : "Webhook notifications are currently disabled for this client."}
          </p>
          <Button
            variant="outline"
            disabled={webhookMutation.isPending}
            onClick={() =>
              webhookMutation.mutate(!data.is_webhook_active, {
                onSuccess: () => toast.success("Webhook status updated"),
                onError: (error) =>
                  toast.error(getErrorMessage(error, "Could not update webhook status")),
              })
            }
          >
            {webhookMutation.isPending && <Loader2 className="size-4 animate-spin" />}
            {data.is_webhook_active ? "Disable" : "Enable"}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
